# Numpy- Numerical Python
<br>
Advantages of Numpy Arrays: <br>
1. Allows several Mathematical Operations  <br>
2. Faster operations

In [1]:
import numpy as np

<b> List vs Numpy - Time Taken

In [2]:
from time import process_time


Time taken by a list

In [6]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)


0.0


In [8]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0


<b> (In numpy array, the operation is faster ) </b>

<b> Numpy Arrays </b>

In [9]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [11]:
# Creating a 1 dim array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a.shape

(4,)

In [13]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
b.shape

(2, 4)

In [16]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


<b> Initial Placeholders in numpy arrays </b>

In [17]:
#create a numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#array of a particular values
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
# create an identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.44511413 0.969275   0.31973283 0.10871587]
 [0.41932473 0.69862287 0.71572275 0.47323615]
 [0.56857491 0.57803133 0.5491311  0.72992324]]


In [22]:
#random integer values array within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[28 17 48 88 20]
 [50 13 36 46 18]
 [35 77 60 47 63]]


In [29]:
# array of evenly spaced values --> specifying the number of values required
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [26]:
#array of evenly spaced values --> specifying the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


<b> Convert a list to a numpy array </b>

In [30]:
# Convert a list to a numpy array 
list2=[10,20,20,20,50]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

<b> Anlysing  a numpy array </b>

In [31]:
c=np.random.randint(10,90,(5,5))
print(c)

[[26 21 57 52 76]
 [88 39 22 80 60]
 [64 14 73 22 52]
 [49 46 37 14 39]
 [73 31 47 72 59]]


In [32]:
# array dimension
print(c.shape)

(5, 5)


In [33]:
# number of dimensions
print(c.ndim)

2


In [34]:
# number of elements in an array
print(c.size)

25


In [35]:
# checking the data type of the values in the array
print(c.dtype)

int32


# Mathematical operations in np array

In [37]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)  # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [38]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[6 3 9]
 [2 8 1]
 [2 0 0]]
[[12 11 12]
 [19 13 16]
 [18 12 16]]


In [40]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 14 21]
 [21 21 17]
 [20 12 16]]
[[ -6  -8  -3]
 [-17  -5 -15]
 [-16 -12 -16]]
[[ 72  33 108]
 [ 38 104  16]
 [ 36   0   0]]
[[0.5        0.27272727 0.75      ]
 [0.10526316 0.61538462 0.0625    ]
 [0.11111111 0.         0.        ]]


In [41]:
print(a)
print(b)

[[6 3 9]
 [2 8 1]
 [2 0 0]]
[[12 11 12]
 [19 13 16]
 [18 12 16]]


In [42]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 14 21]
 [21 21 17]
 [20 12 16]]
[[ -6  -8  -3]
 [-17  -5 -15]
 [-16 -12 -16]]
[[ 72  33 108]
 [ 38 104  16]
 [ 36   0   0]]
[[0.5        0.27272727 0.75      ]
 [0.10526316 0.61538462 0.0625    ]
 [0.11111111 0.         0.        ]]


# Array manipulation

In [43]:
array=a=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 6 9]
 [4 9 4]]
(2, 3)


In [44]:
#transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[1 4]
 [6 9]
 [9 4]]
(3, 2)


In [45]:
array=a=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 3 2]
 [4 2 6]]
(2, 3)


In [46]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[6 4]
 [3 2]
 [2 6]]
(3, 2)


<b> Reshaping an array </b>

In [47]:
# Reshaping an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 9 2]
 [6 7 9]]
(2, 3)


In [48]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[6 9]
 [2 6]
 [7 9]]
(3, 2)
